main: com.admincmd.admincmd.Main
name: ${project.artifactId}
version: ${project.version} (BUILD ${git.build.time})
authors: [Balor, TheJeterLP, JKMalan, BossLetsPlays]
description: This plugin implements the basic commands for running a server.
